MSCX class API. Three methods introduced
johentsch/ms3 pull request #91
Opened 2023-08-28 14:03 UTC by leobruneau

1) make_excerpt() : takes starting and ending (optional) measures and then creates an excerpt after retrieving corresponding globalkey and localkey information
2) extract_phrases() : calls make_excerpt() method for each pair of starting and ending measure corresponding to a phrase
3) extract_random_snippets() : takes as parameters number of snippets and snippet length to randomly create excerpts (calls the make_excerpt() method for each randomly generated pair)

2023-08-28 15:01 UTC, johentsch requested changes

2023-08-28 15:01 UTC, johentsch commented on src/ms3/score.py
> +        print(f"Global key: {global_key}, Local key: {local_key}")
please use `self.logger.debug`

2023-08-28 16:13 UTC, leobruneau commented
Requested changes were met

2023-08-29 12:22 UTC, johentsch requested changes
Hi @leobruneau,

Please go through my added commits carefully (you can [start her](https://github.com/johentsch/ms3/pull/91/commits/c27e7cdcf14a41f7bca6dd428dca787382fbf867) and conveniently use the arrow button for that) to see if you agree with all the changes. Feel free to leave comments, questions, suggestions.

When you're through, please add your name to the contributors list in `AUTHORS.rst`. Then we might be ready to merge, depending on the outcome of your review.

2023-08-29 14:38 UTC, leobruneau reviewed
You made some very nice changes. I'm sorry that you had to re-factor almost everything. I'm not sure I should be added to the contributors.

I think it's all ready to merge

2023-08-30 08:51 UTC, johentsch approved these changes
Thank you, Léo!

2023-08-30 08:51 UTC, merged